export let products = [
  {
    id: 1,
    title: "Ficus",
    price: 50.0,
    stock: 3,
    description: "Lorem Ipsun",
    category: "Indoor",
    img: "https://res.cloudinary.com/dsrxguglp/image/upload/v1711492815/ficus-1.jpg",
  },
  {
    id: 2,
    title: "Gymnocalycium",
    price: 10.0,
    stock: 10,
    description: "Lorem Ipsun",
    category: "Cactus",
    img: "https://res.cloudinary.com/dsrxguglp/image/upload/v1711493301/Gymnocalycium-2.jpg",
  },
  {
    id: 3,
    title: "Echinopsis ",
    price: 15.0,
    stock: 20,
    description: "Lorem Ipsun",
    category: "Cactus",
    img: "https://res.cloudinary.com/dsrxguglp/image/upload/v1711493406/Echinopsis-3.jpg",
  },
  {
    id: 4,
    title: "Lemon Tree ",
    price: 15.0,
    stock: 20,
    description: "Lorem Ipsun",
    category: "Outdoor",
    img: "https://res.cloudinary.com/dsrxguglp/image/upload/v1711493923/lemon-tree-5.png",
  },
  {
    id: 5,
    title: "Pothos ",
    price: 15.0,
    stock: 20,
    description: "Lorem Ipsun",
    category: "Indoor",
    img: "https://res.cloudinary.com/dsrxguglp/image/upload/v1711493743/POTHOS-5.webp",
  },
  {
    id: 6,
    title: "Spider Plant ",
    price: 12.0,
    stock: 8,
    description: "Lorem Ipsun",
    category: "Indoor",
    img: "https://res.cloudinary.com/dsrxguglp/image/upload/v1712707828/y6oggv6pgaxm18qbudtm.jpg",
  },
];
